export {
  type ReviewStore,
  type BaseAnnotation,
  type TextAnnotation,
  type ElementSelector,
  type ElementAnnotation,
  type Annotation,
  type AnnotationStatus,
  type AgentReply,
  type PageNote,
  type SerializedRange,
  createEmptyStore,
  isTextAnnotation,
  isElementAnnotation,
  getAnnotationStatus,
} from '../shared/types.js';
